kubernetesClusterDomain: cluster.local
superMario:
  replicas: 1 
  superMario:
    image:
      repository: kaminskypavel/mario
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
