kind: Deployment
apiVersion: apps/v1
metadata:
  name: super-mario
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-mario
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: super-mario
    spec:
      containers:
        - name: super-mario
          image: kaminskypavel/mario:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
