apiVersion: argoproj.io/v1alpha1
kind: Application
project: default
source:
  repoURL: 'https://github.com/MohammedTariq/tariq_mario.git'
  path: mini/super-mario-helm
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - Replace=true

