apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-super-mario
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.superMario.replicas }}
  selector:
    matchLabels:
      app: super-mario
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: super-mario
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.superMario.superMario.image.repository }}:{{ .Values.superMario.superMario.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.superMario.superMario.imagePullPolicy }}
        name: super-mario
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {{- toYaml .Values.superMario.superMario.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30